name: example
description: A Flutter example project for nyx_converter.

maintainers: ["Hossein HassanNejad"]
links: {"GitHub": "https://github.com/xaus-group/nyx_converter"}

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nyx_converter:
    path: ../
  permission_handler: ^11.3.1
  file_picker: ^7.0.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
