name: nyx_converter
version: 0.1.0
description: >-
  A Flutter package that makes it easier to convert formats, codecs, etc. of media files.
repository: https://github.com/xaus-group/nyx_converter
issue_tracker: https://github.com/xaus-group/nyx_converter/issues
# homepage:
# documentation:
topics: [video, audio, converter, ffmpeg]

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: 3.16.5

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

assets:
  - assets/videos/

screenshots:
  - description: The flutter nyx_converter package logo.
    path: screenshots/logo.png
