on:
  pull_request:
  push:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter test